# Generated by Django 6.1 on 2026-08-13 09:52

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('quantity_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('food_type', models.CharField(blank=True, max_length=100)),
                ('expiry_datetime', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('matched', 'Matched'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], db_index=True, default='available', max_length=20)),
                ('pickup_location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('pickup_address', models.CharField(blank=True, max_length=500)),
                ('donor', models.ForeignKey(limit_choices_to={'role': 'donor'}, on_delete=django.db.models.deletion.PROTECT, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Food Listing',
                'verbose_name_plural': 'Food Listings',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
